galaxy_info:
  author: IBM
  description: Role that executes sanity checks on the appliance
  company: IBM

  license: Apache

  min_ansible_version: 2.9
  
  platforms:
    - name: Fedora
      versions:
        - 30
        - 29
        - 28
        - 27
    - name: EL
      versions:
        - 8
        - 7
        - 6

  galaxy_tags:
  - isam
  - ibm

dependencies:
  - common_handlers
