galaxy_info:
  author: IBM
  description: Role to configure reverse proxy junctions
  company: IBM



  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
  - isam
  - ibm
  - configure
  - reverse_proxy_junctions

dependencies:
  - common_handlers
