---

galaxy_info:
  author: IBM
  description: Role that adds a node to a cluster by importing signature file
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
  - isam
  - ibm
  - cluster
  - signature
  - import
  - node

dependencies:
  - common_handlers
