---

galaxy_info:
  author: IBM
  description: Role to configure runtime template root content
  company: IBM

  license: Apache

  min_ansible_version: 2.8

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
  - isam
  - ibm
  - configure
  - runtime_template_root

dependencies:
  - common_handlers
