galaxy_info:
  author: IBM
  description: Role to create federations
  company: IBM

  license: Apache

  min_ansible_version: 2.8

  platforms:
   - name: EL
     versions:
      - all
   - name: GenericLinux
     versions:
      - all

  galaxy_tags:
  - isam
  - ibm
  - create
  - federation

dependencies: []



