galaxy_info:
  author: IBM
  description: Role to load a signer certificate into a certificate store
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
  - isam
  - ibm
  - load_signer_certificates

dependencies:
  - common_handlers
