---

galaxy_info:
  author: IBM
  description: Retrieve access control policies
  company: IBM

  license:  Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
    - ibm
    - isam
    - access_control
    - policies
    - get

dependencies: []

