---
galaxy_info:
  author: IBM
  description: Role to merge keytab files for krb5 kerberos
  company: IBM



  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all

  galaxy_tags:
    - isam
    - ibm
    - upload
    - keytab
    - krb5
    - krb

dependencies:
  - common_handlers
