galaxy_info:
  author: IBM
  description: Role to get the federation partners
  company: IBM

  license: Apache-2.0

  min_ansible_version: 2.9

  platforms:
    - name: GenericLinux
      versions:
        - all
    - name: EL
      versions:
        - all



  galaxy_tags:
  - isam
  - ibm
  - federation

dependencies:
  - common_handlers
